In [23]:
# Loading the dataset using pandas

import pandas as pd
import numpy as np
!pip install pyodbc sqlalchemy
from sqlalchemy import create_engine,text
from urllib.parse import quote_plus
from time import strptime

df = pd.read_excel('banking_call_data.xlsx')

Requirement already satisfied: pyodbc in c:\users\david\anaconda3\lib\site-packages (4.0.39)
Requirement already satisfied: sqlalchemy in c:\users\david\anaconda3\lib\site-packages (2.0.21)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\david\anaconda3\lib\site-packages (from sqlalchemy) (4.7.1)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\david\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [24]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

In [26]:
df.shape

(45211, 17)

In [27]:
#checking for duplicates
df.duplicated().sum()

0

In [28]:
df.isna().any().any()

False

In [29]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [30]:
df.describe(include='all')

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
count,45211.000000,45211,45211,45211,45211,45211.000000,45211,45211,45211,45211.000000,45211,45211.000000,45211.000000,45211.000000,45211.000000,45211,45211
unique,NaN,12,3,4,2,NaN,2,2,3,NaN,12,NaN,NaN,NaN,NaN,4,2
top,NaN,blue-collar,married,secondary,no,NaN,yes,no,cellular,NaN,may,NaN,NaN,NaN,NaN,unknown,no
freq,NaN,9732,27214,23202,44396,NaN,25130,37967,29285,NaN,13766,NaN,NaN,NaN,NaN,36959,39922
mean,40.936210,NaN,NaN,NaN,NaN,1362.272058,NaN,NaN,NaN,15.806419,NaN,258.163080,2.763841,40.197828,0.580323,NaN,NaN
std,10.618762,NaN,NaN,NaN,NaN,3044.765829,NaN,NaN,NaN,8.322476,NaN,257.527812,3.098021,100.128746,2.303441,NaN,NaN
min,18.000000,NaN,NaN,NaN,NaN,-8019.000000,NaN,NaN,NaN,1.000000,NaN,0.000000,1.000000,-1.000000,0.000000,NaN,NaN
25%,33.000000,NaN,NaN,NaN,NaN,72.000000,NaN,NaN,NaN,8.000000,NaN,103.000000,1.000000,-1.000000,0.000000,NaN,NaN
50%,39.000000,NaN,NaN,NaN,NaN,448.000000,NaN,NaN,NaN,16.000000,NaN,180.000000,2.000000,-1.000000,0.000000,NaN,NaN
75%,48.000000,NaN,NaN,NaN,NaN,1428.000000,NaN,NaN,NaN,21.000000,NaN,319.000000,3.000000,-1.000000,0.000000,NaN,NaN
max,95.000000,NaN,NaN,NaN,NaN,102127.000000,NaN,NaN,NaN,31.000000,NaN,4918.000000,63.000000,871.000000,275.000000,NaN,NaN

# Investigating Numerical and Categorical Columns

In [31]:
#Separating Numerical & Categorical Columns
df_num_features = df.select_dtypes(include=[np.number])
df_cat_features = df.select_dtypes(exclude=[np.number])

In [32]:
df_num_features

       age  balance  day  duration  campaign  pdays  previous
0       58     2143    5       261         1     -1         0
1       44       29    5       151         1     -1         0
2       33        2    5        76         1     -1         0
3       47     1506    5        92         1     -1         0
4       33        1    5       198         1     -1         0
...    ...      ...  ...       ...       ...    ...       ...
45206   51      825   17       977         3     -1         0
45207   71     1729   17       456         2     -1         0
45208   72     5715   17      1127         5    184         3
45209   57      668   17       508         4     -1         0
45210   37     2971   17       361         2    188        11

[45211 rows x 7 columns]

In [33]:
df_cat_features

,job,marital,education,default,housing,loan,contact,month,poutcome,y
0,management,married,tertiary,no,yes,no,unknown,may,unknown,no
1,technician,single,secondary,no,yes,no,unknown,may,unknown,no
2,entrepreneur,married,secondary,no,yes,yes,unknown,may,unknown,no
3,blue-collar,married,unknown,no,yes,no,unknown,may,unknown,no
4,unknown,single,unknown,no,no,no,unknown,may,unknown,no
...,...,...,...,...,...,...,...,...,...,...
45206,technician,married,tertiary,no,no,no,cellular,nov,unknown,yes
45207,retired,divorced,primary,no,no,no,cellular,nov,unknown,yes
45208,retired,married,secondary,no,no,no,cellular,nov,success,yes
45209,blue-collar,married,secondary,no,no,no,telephone,nov,unknown,no
45210,entrepreneur,married,secondary,no,no,no,cellular,nov,other,no

In [34]:
#Checking All Unique values in Each Categorical Column for Inconsistent Data

print(f"Unique values For All Categorical Columns\n".upper())

for categorical_features in df_cat_features:
    unique_values = df[categorical_features].unique()
    print(f"\n{categorical_features}: \n{unique_values}\n")
    print('-' * 40)

UNIQUE VALUES FOR ALL CATEGORICAL COLUMNS


job:
['management' 'technician' 'entrepreneur' 'blue-collar' 'unknown'
 'retired' 'admin.' 'services' 'self-employed' 'unemployed' 'housemaid'
 'student']

----------------------------------------

marital:
['married' 'single' 'divorced']

----------------------------------------

education:
['tertiary' 'secondary' 'unknown' 'primary']

----------------------------------------

default:
['no' 'yes']

----------------------------------------

housing:
['yes' 'no']

----------------------------------------

loan:
['no' 'yes']

----------------------------------------

contact:
['unknown' 'cellular' 'telephone']

----------------------------------------

month:
['may' 'jun' 'jul' 'aug' 'oct' 'nov' 'dec' 'jan' 'feb' 'mar' 'apr' 'sep']

----------------------------------------

poutcome:
['unknown' 'failure' 'other' 'success']

----------------------------------------

y:
['no' 'yes']

----------------------------------------

# Feature Engineering


- Column [duration] recorded in secondS, will changed to minutes  

- Grouping column [age] will 4 categories

- Renaming column [y] to deposit 

- Convert month mame to numbers

In [35]:
# Creating [minute] column and converting [duration] in seconds to minutes 
df['duration_min'] = df['duration'] / 60

In [36]:
# Creating [age_group] column and grouping [age] column 
bins = [0, 25, 40, 60, 120]
labels = ['Young Adult', 'Adult', 'Middle-Aged', 'Senior']

df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels)

df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y,duration_min,age_group
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no,4.350000,Middle-Aged
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no,2.516667,Middle-Aged
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no,1.266667,Adult
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no,1.533333,Middle-Aged
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no,3.300000,Adult

In [37]:
# renaming column y to deposit
df = df.rename(columns={'y': 'deposit'})

In [38]:
# converting months into numbers
df['month_number'] = [strptime(str(x), '%b').tm_mon for x in df['month']]

In [39]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit,duration_min,age_group,month_number
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no,4.350000,Middle-Aged,5
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no,2.516667,Middle-Aged,5
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no,1.266667,Adult,5
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no,1.533333,Middle-Aged,5
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no,3.300000,Adult,5

# Connecting to MS SQL Server

In [40]:
# SQL Server connection
username = "sa"
password = "Sql_123$#"
host = "localhost"
port = "1433"
database = "marketing_analytics"
#driver = "ODBC Driver 17 for SQL Server"

# Microsoft ODBC Driver 
driver = quote_plus("ODBC Driver 17 for SQL Server")
engine = create_engine(f"mssql+pyodbc://{username}:{password}@{host},{port}/{database}?driver={driver}")

# Writing DataFrame to SQL Server
df.to_sql("fact_marketing_campaign", engine, if_exists="replace", index=False)

# Reading back sample
with engine.connect() as conn:
    result = pd.read_sql(text("SELECT TOP 5 * FROM fact_marketing_campaign;"), conn)

print("Data Successfully Loaded to Database")

Data Successfully Loaded to Database